/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/_admin.route'
import { Route as AdminIndexRouteImport } from './routes/_admin.index'
import { Route as AdminSanPhamRouteImport } from './routes/_admin.san-pham'
import { Route as AdminCongTrinhThiCongRouteImport } from './routes/_admin.cong-trinh-thi-cong'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSanPhamRoute = AdminSanPhamRouteImport.update({
  id: '/san-pham',
  path: '/san-pham',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCongTrinhThiCongRoute = AdminCongTrinhThiCongRouteImport.update({
  id: '/cong-trinh-thi-cong',
  path: '/cong-trinh-thi-cong',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/cong-trinh-thi-cong': typeof AdminCongTrinhThiCongRoute
  '/san-pham': typeof AdminSanPhamRoute
}
export interface FileRoutesByTo {
  '/cong-trinh-thi-cong': typeof AdminCongTrinhThiCongRoute
  '/san-pham': typeof AdminSanPhamRoute
  '/': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_admin/cong-trinh-thi-cong': typeof AdminCongTrinhThiCongRoute
  '/_admin/san-pham': typeof AdminSanPhamRoute
  '/_admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cong-trinh-thi-cong' | '/san-pham'
  fileRoutesByTo: FileRoutesByTo
  to: '/cong-trinh-thi-cong' | '/san-pham' | '/'
  id:
    | '__root__'
    | '/_admin'
    | '/_admin/cong-trinh-thi-cong'
    | '/_admin/san-pham'
    | '/_admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/san-pham': {
      id: '/_admin/san-pham'
      path: '/san-pham'
      fullPath: '/san-pham'
      preLoaderRoute: typeof AdminSanPhamRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/cong-trinh-thi-cong': {
      id: '/_admin/cong-trinh-thi-cong'
      path: '/cong-trinh-thi-cong'
      fullPath: '/cong-trinh-thi-cong'
      preLoaderRoute: typeof AdminCongTrinhThiCongRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCongTrinhThiCongRoute: typeof AdminCongTrinhThiCongRoute
  AdminSanPhamRoute: typeof AdminSanPhamRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCongTrinhThiCongRoute: AdminCongTrinhThiCongRoute,
  AdminSanPhamRoute: AdminSanPhamRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
